### ISSUE TITLE
Remove do -> from buildFacesFromFaceVertexMesh

### ISSUE THREAD

**Issue by Steditor** [brickify/meshlib#30]
https://github.com/brickify/meshlib/blob/develop/source/helpers/buildFacesFromFaceVertexMesh.coffee#L5
and
https://github.com/brickify/meshlib/blob/develop/source/helpers/buildFacesFromFaceVertexMesh.coffee#L12

**Comment by adius** [comment]
Fixed by 3fe0621cc15df44601e29efeb9e499ffb732205a
