### ISSUE TITLE
Rewrite model splitting

### ISSUE THREAD

**Issue by Steditor** [brickify/meshlib#6]
The current implementation has several issues: connected components are eagerly merged instead of doing the merging in a final step and triangles are added to the geometry several times.

**Comment by adius** [comment]
This issue was moved to Lowfab/stl-importer#2

**Comment by Steditor** [comment]
I think this should be done in meshlib, as it is not a format-specific issue.

**Comment by adius** [comment]
Fixed by c166068da88ebcbfe22e6f56d94aa56ff77cc151
